### ISSUE TITLE
Cleaning up display issues in Reference List

### ISSUE THREAD

**Issue by araiffe** [Princeton-CDH/derrida-django#134]
- [x] render formatting in references text #135 
- [x] adjust cited in filter so full title displays #136
- [ ] updated wording for filters #169 
- [x] determine how to handle page number cleanup

***

Hi @xinyil and @rlskoeser,

@kac3 and I spoke today and we have a couple of questions on the visualization of Reference List.

1. Is it possible in the cited text to display the formatting of italics? Right now, text that should be italicized is appearing as *_* instead of italicized (i.e. *Critique* in the screenshot below)
![screen shot 2017-10-06 at 13 23 52](https://user-images.githubusercontent.com/26753387/31290225-a76b4976-aa99-11e7-8bde-a190f642e5db.png)

2. Is it possible to get rid of the a/b/c/d after the page number of "Cited in _De la grammatologie_ p. #_)? 

3. Is it possible to modify the filter so that "Cited by Derrida in: De la grammatologie" shows entirely? Right now, it shows up as "De la grammatologi" and the e is cut off on the right side.

4. Can we get rid of the p after the page in the cited work? In this example: it's p. 87p but should just be p. 87.
![screen shot 2017-10-06 at 13 26 12](https://user-images.githubusercontent.com/26753387/31290292-f69da156-aa99-11e7-8809-dfad95f8776d.png)

5. Can we replace the s by "_sq." (the underscore represents a space). See below for an example (p. 44s, and we would like it to be "p. 44 sq.": 
![screen shot 2017-10-06 at 13 27 03](https://user-images.githubusercontent.com/26753387/31290320-0d8ce78c-aa9a-11e7-9182-806eafe3726e.png)

6. On the verbiage of filter itself, there's a subject-verb agreement problem. It says "Only show cited books that: - extant in Derrida's Library; - Contains annotations; -Contains corresponding annotations". It should say something like "Only show cited books that - Are extant in Derrida's Library, - Contain annotations, - Contain corresponding annotations" but I'll defer to @kac3 for exactly how the text should read.

**Comment by rlskoeser** [comment]
@araiffe @kac3 thank you for documenting these items, this is helpful.

1. I noticed the formatting issue in passing but forgot to document that we need to render it.  We'll get that fixed.
2. Yes, we'll go ahead and remove the page location from public display.
3. I see what you mean about the filter.  We should be able to fix that too.
4. The p and s in the page numbers are coming from your data.  I've wondered about this and suspected it was a data clean up issue, so I'm glad you noticed it (I can't remember if I've asked about it before or not; must have gotten lost in the shuffle one way or another).  I think the best way for you to clean this up is to go through the references in the admin interface.  The book page field is displayed on the list view, so you can identify items that need to be cleaned up.  (If this could be done programmatically rather than manually we could do it for you, but you'll need to review everything first to check that it's safe and tell us _exactly_ what needs to be changed.)
5. Same issue as 4 - we're displaying what's in the database.  The variety that I'm seeing for book pages makes me nervous about trying to clean it up programmatically, because I worry about introducing more errors!
6.  Thank you for noticing that!  The wording has been bothering me too.  I'll hold off on editing it until we hear from @kac3 on specifics.

**Comment by rlskoeser** [comment]
I'm going to create separate tasks for the development & design items, so that we can track and sign off on them independently.

**Comment by rlskoeser** [comment]
@kac3 I think the page number cleanup that Alex raised in this issue has been addressed.

I think there are still some wording/language issues with the filters, but I'm not sure the best way to address.  If we add screenshots from the design, based on that and what's on the test site could you provide any changes to wording you'd like to see?

**Comment by kac3** [comment]
@rlskoeser Yes, I can do that!  I think that's a good way to go about it.

**Comment by rlskoeser** [comment]
@kac3 here's the design for the library page filter:

<img width="1169" alt="screen shot 2018-04-02 at 3 09 49 pm" src="https://user-images.githubusercontent.com/691231/38211268-ef198d62-3687-11e8-9597-7c7bf010b08f.png">

@kac3 here's the design for the reference list:
<img width="1239" alt="screen shot 2018-04-02 at 3 10 23 pm" src="https://user-images.githubusercontent.com/691231/38211301-015b3aca-3688-11e8-8d25-d9ed4e799d99.png">

Here's the design for intervention filters, it doesn't seem to include any wording at the top (and what we have on the test site doesn't make sense).
<img width="1223" alt="screen shot 2018-04-02 at 3 11 53 pm" src="https://user-images.githubusercontent.com/691231/38211366-38a9e8dc-3688-11e8-91dc-3025e631bb62.png">

The references and interventions are more complicated because some of the features are specific to the reference or intervention, but more of them related to the item that is referenced or annotated.

What we have on the test site doesn't match the design quite - please identify the changes that are high priority for you to make these filters usable.

**Comment by xinyil** [comment]
we're tracking wording and sequence issues in #169

**Comment by rlskoeser** [comment]
Thanks @xinyil, I did see that in passing...

@kac3 please document your decisions on wording / priority fixes on #169.  If it would be helpful to have the same screenshots above on that ticket, I can move them over and then I think we can close this one.
