### ISSUE TITLE
[Priority List] Front-End clean up design+styles

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#165]
## High priority
these issues influence site interaction 
- [x] #185 - unclickable nav on canvas detail page
- [ ] #142 - Filters - Drop down menu
- [ ] #141 - Search field status
- [x] #162 - Filters - going back is not cleaning filters, but the results have been cleaned
- [x] #157 - Deep zoom viewer does not close
- [ ] #151 - View Page - page behavior
- [x] #85 - Citation card - link behavior
- [ ] #76 - Navigation L M S
- [x] #167 - Filters - default to Cited by Derrida in DG
- [x] #169 - Filters - sequence issue and inconsistent UI language
- [x] #176 - Introduction text on banner - spacing and style
- [x]  #199

## crucial display problems
- [x] #161 - Citation card grid setting
- [x] #152 - Outwork, possibly error page? - missing images and content, alignment issue

## Display problems, won't affect function
- [x] #137 - Book - typography of title and author
- [x] #160 - Banner image resizing
- [x] #155 -  Typography - text color
- [x] #143 - Typography - extra outline of normal weight text
- [x] #116 - Typography - bold style usage
- [x] #168 - Check box - extra outline in chrome, MD ripple should be disabled
- [x] #193 - Book page - tab
- [x] #194 - Sorting buttons being cut off
- [x] #195 - Labels - add spacing for stacked labels

**Comment by bwhicks** [comment]
I've also hit this issue, and I think it may be Firefox specific, but the search bar has a 1 px misalignment.

<img width="1077" alt="screen shot 2018-03-29 at 9 17 34 am" src="https://user-images.githubusercontent.com/17815297/38091084-7c3768da-3332-11e8-9f69-22b34b13ebef.png">

**Comment by thatbudakguy** [comment]
This doesn't include any information not captured in other issues, so I'm going to close it.
